name: core
description: Core 로직 모음 - 핵심 비즈니스 로직을 포함합니다.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../data/
  util:
    path: ../util/

  equatable: ^2.0.3
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
